version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    networks:
      - inception
    volumes:
      - data1:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env
    restart: always
    image: mariadb
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - data2:/var/www/html
    env_file: 
      - .env
    restart: always
    image: wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - data2:/var/www/html
    env_file: 
      - .env
    restart: always
    image: nginx
networks:
  inception:
    name: inception
    driver: bridge
volumes:
  data2:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/met-tahe/data/wordpress
      o: bind
  data1:
    name: mdb_data
    driver: local
    driver_opts:
      type: none
      device: /home/met-tahe/data/mariadb
      o: bind
