version: "3"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - mynet1
    volumes:
      - data1:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - ./.env
    networks:
      - mynet1
    volumes:
      - data2:/var/www/html
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - ./.env
    networks:
      - mynet1
    volumes:
      - data2:/var/lib/mysql
    restart: always
networks:
  mynet1:
    driver: bridge
volumes:
  data2:
    name: wp_data
    driver: local
    driver_opts:
            device: /home/escanor
            o: bind
            type: none
  data1:
    name: db_data
    driver: local
    driver_opts:
      device: /home/escanor
      o: bind
      type: none
