version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - mynet1
    volumes:
      - data1:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - mynet1
    volumes:
      - data2:/var/www/html
    env_file: 
      - .env
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - mynet1
    volumes:
      - data2:/var/www/html
    restart: always
networks:
  mynet1:
    driver: bridge
volumes:
  data2:
  data1:
